name: recommend_you
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.1
  http_interceptor:
  intl:

  #for state management
  get:
  get_storage:

  #for Notification
  flutter_local_notifications:

  #for dynamic ui
  flutter_screenutil:

  #for custom toast
  fluttertoast:

  #for custom fonts
  google_fonts:
  font_awesome_flutter:

  flutter_svg:

  easy_debounce:

  image_picker:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/settings/
    - assets/profileImage/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/playfair/PlayfairDisplay-Bold.ttf
        - asset: assets/fonts/playfair/PlayfairDisplay-SemiBold.ttf
        - asset: assets/fonts/playfair/PlayfairDisplay-Bold.ttf
        - asset: assets/fonts/playfair/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/playfair/PlayfairDisplay-Medium.ttf
        - asset: assets/fonts/playfair/PlayfairDisplay-Black.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700

    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf